name: Auto-Fix on Failure

on:
  workflow_run:
    workflows: ["Amplify Backend Pipeline"]
    types:
      - completed

permissions:
  contents: write
  actions: read

jobs:
  auto-fix-failed-build:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.workflow_run.head_branch }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run comprehensive auto-fix
        run: |
          echo "🔧 Running comprehensive auto-fix..."
          node scripts/auto-fix.js || true
      
      - name: Check if fixes were made
        id: check-changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "✅ Auto-fixes were applied"
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "ℹ️ No auto-fixable issues found"
          fi
      
      - name: Commit and push fixes
        if: steps.check-changes.outputs.changes == 'true'
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          git add -A
          git commit -m "🤖 Auto-fix errors from failed build #${{ github.event.workflow_run.id }}"
          git push origin ${{ github.event.workflow_run.head_branch }}
          
          echo "✅ Fixes committed! A new build will be triggered automatically."
